
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class RestaurantJFrame extends javax.swing.JFrame {

    static ArrayList<Food> foodReceipt = new ArrayList<>();
    static Connection conn = null;
    static ResultSet rs = null;
    static PreparedStatement pat = null;
    static Statement stm = null;
    double[] i = new double[5];

    public RestaurantJFrame() {
        initComponents();
        conn = MysqlConnetion.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FoodPanel = new javax.swing.JPanel();
        NumOfFirstFood = new javax.swing.JTextField();
        NumOfSecondFood = new javax.swing.JTextField();
        NumOfThirdFood = new javax.swing.JTextField();
        ChickenCB = new javax.swing.JCheckBox();
        HamburgerCB = new javax.swing.JCheckBox();
        BaconCB = new javax.swing.JCheckBox();
        Drinksjlb = new javax.swing.JLabel();
        SelectDrinksCB = new javax.swing.JComboBox<>();
        TaxCb = new javax.swing.JCheckBox();
        HomeDeliveryCB = new javax.swing.JCheckBox();
        ConvertPanel = new javax.swing.JPanel();
        ChangeMoneyCB = new javax.swing.JComboBox<>();
        TypeMoneyTxt = new javax.swing.JTextField();
        ShowMoneyJlb = new javax.swing.JLabel();
        ConvertBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        CostPanel = new javax.swing.JPanel();
        CostofDrinksJLB = new javax.swing.JLabel();
        CostofMealsJlb = new javax.swing.JLabel();
        CostofHomeJlb = new javax.swing.JLabel();
        ShowCostOfDrinksJlb = new javax.swing.JLabel();
        ShowCostOfMealsJLB = new javax.swing.JLabel();
        ShowCostOfDelieryJLB = new javax.swing.JLabel();
        TotalPanel = new javax.swing.JPanel();
        SubTotalJLB = new javax.swing.JLabel();
        TaxJLB = new javax.swing.JLabel();
        TotalJLb = new javax.swing.JLabel();
        ShowSubJLB = new javax.swing.JLabel();
        ShowTaxJLB = new javax.swing.JLabel();
        ShowTotalJLB = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        TotalBtn = new javax.swing.JButton();
        ReceiptBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ReceiptPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReceiptArea = new javax.swing.JTextArea();
        TittleTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FoodPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        NumOfFirstFood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumOfFirstFood.setText("0");
        NumOfFirstFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NumOfSecondFood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumOfSecondFood.setText("0");
        NumOfSecondFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        NumOfSecondFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfSecondFoodActionPerformed(evt);
            }
        });

        NumOfThirdFood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumOfThirdFood.setText("0");
        NumOfThirdFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        NumOfThirdFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfThirdFoodActionPerformed(evt);
            }
        });

        ChickenCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChickenCB.setText("Chicken");
        ChickenCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChickenCBMouseClicked(evt);
            }
        });
        ChickenCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenCBActionPerformed(evt);
            }
        });

        HamburgerCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HamburgerCB.setText("Hamburger");
        HamburgerCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HamburgerCBMouseClicked(evt);
            }
        });
        HamburgerCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HamburgerCBActionPerformed(evt);
            }
        });

        BaconCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BaconCB.setText("Bacon");
        BaconCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaconCBMouseClicked(evt);
            }
        });
        BaconCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaconCBActionPerformed(evt);
            }
        });

        Drinksjlb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Drinksjlb.setText("Drinks");

        SelectDrinksCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectDrinksCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select drinks", "Coca", "Coffee", "Ice Coffee", "Tea", "Ice Tea", "Apple Juice", "Milk" }));
        SelectDrinksCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectDrinksCBActionPerformed(evt);
            }
        });

        TaxCb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TaxCb.setText("Tax");
        TaxCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxCbActionPerformed(evt);
            }
        });

        HomeDeliveryCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HomeDeliveryCB.setText("Home Delivery");
        HomeDeliveryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeDeliveryCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FoodPanelLayout = new javax.swing.GroupLayout(FoodPanel);
        FoodPanel.setLayout(FoodPanelLayout);
        FoodPanelLayout.setHorizontalGroup(
            FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoodPanelLayout.createSequentialGroup()
                .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FoodPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChickenCB)
                            .addComponent(HamburgerCB)
                            .addComponent(BaconCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NumOfFirstFood, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(NumOfSecondFood)
                            .addComponent(NumOfThirdFood)))
                    .addGroup(FoodPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FoodPanelLayout.createSequentialGroup()
                                .addComponent(TaxCb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HomeDeliveryCB))
                            .addGroup(FoodPanelLayout.createSequentialGroup()
                                .addComponent(Drinksjlb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SelectDrinksCB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        FoodPanelLayout.setVerticalGroup(
            FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumOfFirstFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChickenCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumOfSecondFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HamburgerCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NumOfThirdFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BaconCB))
                .addGap(18, 18, 18)
                .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drinksjlb)
                    .addComponent(SelectDrinksCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaxCb)
                    .addComponent(HomeDeliveryCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConvertPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ChangeMoneyCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChangeMoneyCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "British", "Singapore", "VietNam", "ThaiLand", "Laos", " " }));
        ChangeMoneyCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeMoneyCBActionPerformed(evt);
            }
        });

        TypeMoneyTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TypeMoneyTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TypeMoneyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeMoneyTxtActionPerformed(evt);
            }
        });

        ShowMoneyJlb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ConvertBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ConvertBtn.setText("Convert");
        ConvertBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ConvertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBtnActionPerformed(evt);
            }
        });

        CloseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConvertPanelLayout = new javax.swing.GroupLayout(ConvertPanel);
        ConvertPanel.setLayout(ConvertPanelLayout);
        ConvertPanelLayout.setHorizontalGroup(
            ConvertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConvertPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(ConvertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShowMoneyJlb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TypeMoneyTxt)
                    .addGroup(ConvertPanelLayout.createSequentialGroup()
                        .addComponent(ConvertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ChangeMoneyCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 149, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        ConvertPanelLayout.setVerticalGroup(
            ConvertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConvertPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChangeMoneyCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TypeMoneyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ShowMoneyJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ConvertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConvertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(CloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CostPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        CostofDrinksJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CostofDrinksJLB.setText("Cost of Drinks");

        CostofMealsJlb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CostofMealsJlb.setText("Cost of Meals");

        CostofHomeJlb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CostofHomeJlb.setText("Cost of Delivery");

        ShowCostOfDrinksJlb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowCostOfDrinksJlb.setText("0");
        ShowCostOfDrinksJlb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ShowCostOfMealsJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowCostOfMealsJLB.setText("0");
        ShowCostOfMealsJLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ShowCostOfDelieryJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowCostOfDelieryJLB.setText("0");
        ShowCostOfDelieryJLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout CostPanelLayout = new javax.swing.GroupLayout(CostPanel);
        CostPanel.setLayout(CostPanelLayout);
        CostPanelLayout.setHorizontalGroup(
            CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CostPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addComponent(CostofHomeJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowCostOfDelieryJLB, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CostofDrinksJLB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CostofMealsJlb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowCostOfDrinksJlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowCostOfMealsJLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        CostPanelLayout.setVerticalGroup(
            CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CostPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShowCostOfDrinksJlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CostofDrinksJLB, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowCostOfMealsJLB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CostofMealsJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostofHomeJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowCostOfDelieryJLB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        SubTotalJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubTotalJLB.setText("Sub Total");

        TaxJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TaxJLB.setText("Tax");

        TotalJLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalJLb.setText("Total");

        ShowSubJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowSubJLB.setText("0");
        ShowSubJLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ShowTaxJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowTaxJLB.setText("0");
        ShowTaxJLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ShowTotalJLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowTotalJLB.setText("0");
        ShowTotalJLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout TotalPanelLayout = new javax.swing.GroupLayout(TotalPanel);
        TotalPanel.setLayout(TotalPanelLayout);
        TotalPanelLayout.setHorizontalGroup(
            TotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalJLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaxJLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubTotalJLB, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowSubJLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowTaxJLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowTotalJLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TotalPanelLayout.setVerticalGroup(
            TotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubTotalJLB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowSubJLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaxJLB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowTaxJLB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalJLb, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(ShowTotalJLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TotalBtn.setText("Total");
        TotalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalBtnMouseClicked(evt);
            }
        });

        ReceiptBtn.setText("Receipt");
        ReceiptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReceiptBtnMouseClicked(evt);
            }
        });
        ReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Reset");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        jButton1.setText("All Receipt");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalBtn)
                .addGap(40, 40, 40)
                .addComponent(ReceiptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ResetBtn)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(ExitBtn)
                .addGap(23, 23, 23))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalBtn)
                    .addComponent(ReceiptBtn)
                    .addComponent(ResetBtn)
                    .addComponent(ExitBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        ReceiptPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ReceiptArea.setColumns(20);
        ReceiptArea.setRows(5);
        jScrollPane1.setViewportView(ReceiptArea);

        javax.swing.GroupLayout ReceiptPanelLayout = new javax.swing.GroupLayout(ReceiptPanel);
        ReceiptPanel.setLayout(ReceiptPanelLayout);
        ReceiptPanelLayout.setHorizontalGroup(
            ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        ReceiptPanelLayout.setVerticalGroup(
            ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TittleTxt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TittleTxt.setText("RESTAURANT SYSTEM");
        TittleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TittleTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FoodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TotalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConvertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ReceiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(TittleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TittleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FoodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConvertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ReceiptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(218, 218, 218))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TittleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TittleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TittleTxtActionPerformed

    private void NumOfSecondFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumOfSecondFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumOfSecondFoodActionPerformed

    private void NumOfThirdFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumOfThirdFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumOfThirdFoodActionPerformed

    private void ConvertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBtnActionPerformed
        double British_Pound = 0.8;
        double VietNamese_VND = 22345.0;
        double Singapore_Dollar = 1.42;
        double Lao_Kip = 8171.45;
        double Thai_Bath = 35.47;

        double Dollar = Double.parseDouble(TypeMoneyTxt.getText());
        if (ChangeMoneyCB.getSelectedItem().equals("British")) {

            double cConvert1 = ( Dollar * British_Pound );
            ShowMoneyJlb.setText(Double.toString(cConvert1) + " Pounds");

        }

        if (ChangeMoneyCB.getSelectedItem().equals("VietNam")) {

            double cConvert1 = ( Dollar * VietNamese_VND );
            ShowMoneyJlb.setText(Double.toString(cConvert1) + " VND");

        }

        if (ChangeMoneyCB.getSelectedItem().equals("Singapore")) {

            double cConvert1 = ( Dollar * Singapore_Dollar );
            ShowMoneyJlb.setText(Double.toString(cConvert1) + " dollar");
        }

        if (ChangeMoneyCB.getSelectedItem().equals("Laos")) {

            double cConvert1 = ( Dollar * Lao_Kip );
            ShowMoneyJlb.setText(Double.toString(cConvert1) + " kip");

        }

        if (ChangeMoneyCB.getSelectedItem().equals("ThaiLand")) {

            double cConvert1 = ( Dollar * Thai_Bath );
            ShowMoneyJlb.setText(Double.toString(cConvert1) + " bath");

        }

    }//GEN-LAST:event_ConvertBtnActionPerformed


    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed

    }//GEN-LAST:event_ResetBtnActionPerformed

    private void SelectDrinksCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectDrinksCBActionPerformed
        double Coca = 0.80;
        double Coffee = 2.0;
        double Ice_Coffee = 2.20;
        double Tea = 0.50;
        double Ice_Tea = 0.80;
        double Apple_Juice = 1.80;
        double Milk = 2.0;

        if (SelectDrinksCB.getSelectedItem().equals("Coca")) {

            String cDrinks = String.format("%.2f", Coca);
            ShowCostOfDrinksJlb.setText(cDrinks);

        }

        if (SelectDrinksCB.getSelectedItem().equals("Coffee")) {

            String cDrinks = String.format("%.2f", Coffee);
            ShowCostOfDrinksJlb.setText(cDrinks);

        }

        if (SelectDrinksCB.getSelectedItem().equals("Ice Coffee")) {

            String cDrinks = String.format("%.2f", Ice_Coffee);
            ShowCostOfDrinksJlb.setText(cDrinks);

        }

        if (SelectDrinksCB.getSelectedItem().equals("Tea")) {

            String cDrinks = String.format("%.2f", Tea);
            ShowCostOfDrinksJlb.setText(cDrinks);

        }

        if (SelectDrinksCB.getSelectedItem().equals("Ice Tea")) {

            String cDrinks = String.format("%.2f", Ice_Tea);
            ShowCostOfDrinksJlb.setText(cDrinks);

        }

        if (SelectDrinksCB.getSelectedItem().equals("Apple Juice")) {

            String cDrinks = String.format("%.2f", Apple_Juice);
            ShowCostOfDrinksJlb.setText(cDrinks);
        }

        if (SelectDrinksCB.getSelectedItem().equals("Milk")) {

            String cDrinks = String.format("%.2f", Milk);
            ShowCostOfDrinksJlb.setText(cDrinks);
        }

        if (SelectDrinksCB.getSelectedItem().equals("Select drinks")) {

            ShowCostOfDrinksJlb.setText("0");
        }

    }//GEN-LAST:event_SelectDrinksCBActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        TypeMoneyTxt.setText(" ");
        ShowMoneyJlb.setText(" ");

    }//GEN-LAST:event_CloseBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void HomeDeliveryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeDeliveryCBActionPerformed
        double CostDelivery = 3.0;
        if (HomeDeliveryCB.isSelected()) {
            String CostOfDelivery = String.format("%.2f", CostDelivery);
            ShowCostOfDelieryJLB.setText(CostOfDelivery);

        } else {
            ShowCostOfDelieryJLB.setText("0");
        }

    }//GEN-LAST:event_HomeDeliveryCBActionPerformed

    private void TaxCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxCbActionPerformed
        double Tax = 0;
        Tax = (i[1] + i[2] + i[0]) / 50;
        if (TaxCb.isSelected()) {
            String CostTax = String.format("%.2f", Tax);
            ShowTaxJLB.setText(CostTax);
        } else {
            ShowTaxJLB.setText("0.0");
        }

    }//GEN-LAST:event_TaxCbActionPerformed

    private void TypeMoneyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeMoneyTxtActionPerformed

    }//GEN-LAST:event_TypeMoneyTxtActionPerformed

    private void ChickenCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenCBActionPerformed

    }//GEN-LAST:event_ChickenCBActionPerformed

    private void ChickenCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChickenCBMouseClicked
        double cMeal = Double.parseDouble(ShowCostOfMealsJLB.getText());
        double Chicken = Double.parseDouble(NumOfFirstFood.getText());
        double iChicken = 5.5;

        if (ChickenCB.isSelected()) {
            i[0] = ((Chicken * iChicken) + cMeal);
            String pMeal = String.format("%.2f", i[0]);
            ShowCostOfMealsJLB.setText(pMeal);

        }
        else {
            NumOfFirstFood.setText("0");
            i[0]=cMeal- (Chicken * iChicken);
            String pMeal = String.format("%.2f", i[0]);
             ShowCostOfMealsJLB.setText(pMeal);
        }
    }//GEN-LAST:event_ChickenCBMouseClicked

    private void HamburgerCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HamburgerCBMouseClicked
        double cMeal = Double.parseDouble(ShowCostOfMealsJLB.getText());
        double Hamburger = Double.parseDouble(NumOfSecondFood.getText());
        double iHamburger = 3.5;

        if (HamburgerCB.isSelected()) {
            i[1] = ((Hamburger * iHamburger) + cMeal);
            String pMeal = String.format("%.2f", i[1]);
            ShowCostOfMealsJLB.setText(pMeal);

        }
        else {
            NumOfSecondFood.setText("0");
            i[1]=cMeal- (Hamburger * iHamburger);
            String pMeal = String.format("%.2f", i[1]);
            ShowCostOfMealsJLB.setText(pMeal);
        }
    }//GEN-LAST:event_HamburgerCBMouseClicked

    private void BaconCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaconCBMouseClicked
        double cMeal = Double.parseDouble(ShowCostOfMealsJLB.getText());
        double Bacon = Double.parseDouble(NumOfThirdFood.getText());
        double iBacon = 6.5;

        if (BaconCB.isSelected()) {
            i[2] = ((Bacon * iBacon) + cMeal);
            String pMeal = String.format("%.2f", i[2]);
            ShowCostOfMealsJLB.setText(pMeal);

        }
        else {
            NumOfThirdFood.setText("0");
            i[2]=cMeal- (Bacon * iBacon);
            String pMeal = String.format("%.2f", i[2]);
            ShowCostOfMealsJLB.setText(pMeal);
        }
    }//GEN-LAST:event_BaconCBMouseClicked

    private void HamburgerCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HamburgerCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HamburgerCBActionPerformed

    private void BaconCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaconCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaconCBActionPerformed

    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
        ShowCostOfMealsJLB.setText("0");
        ShowCostOfDelieryJLB.setText("0");
        ShowSubJLB.setText("0");
        ShowTaxJLB.setText("0");
        ShowTotalJLB.setText("0");
        NumOfFirstFood.setText("0");
        NumOfSecondFood.setText("0");
        NumOfThirdFood.setText("0");
        ChickenCB.setSelected(false);
        BaconCB.setSelected(false);
        HamburgerCB.setSelected(false);
        HomeDeliveryCB.setSelected(false);
        TaxCb.setSelected(false);
        SelectDrinksCB.setSelectedItem("Select drinks");
        ChangeMoneyCB.setSelectedItem("Choose one...");
        ReceiptArea.setText(null);
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void ChangeMoneyCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeMoneyCBActionPerformed
        if (ChangeMoneyCB.getSelectedItem().equals("Choose one...")) {
            ShowMoneyJlb.setText(null);
            TypeMoneyTxt.setText(null);
        }
    }//GEN-LAST:event_ChangeMoneyCBActionPerformed

    private void TotalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalBtnMouseClicked
        double SubTotal = SubTotalFunction();
        ShowSubJLB.setText(Double.toString(SubTotal));

        double chicken = Double.parseDouble(NumOfFirstFood.getText());
        double hamburger = Double.parseDouble(NumOfSecondFood.getText());
        double bacon = Double.parseDouble(NumOfThirdFood.getText());
        double costOfDelivery = Double.parseDouble(ShowCostOfDelieryJLB.getText());
        double costOfDrink = Double.parseDouble(ShowCostOfDrinksJlb.getText());
        double costOfMeal = Double.parseDouble(ShowCostOfMealsJLB.getText());
        double costOfTax = Double.parseDouble(ShowTaxJLB.getText());
        double costOfSub = Double.parseDouble(ShowSubJLB.getText());

        double Total = (costOfDelivery + costOfDrink + costOfMeal + costOfTax - costOfSub);

        String iTotal = String.format("%.2f", Total);

        ShowTotalJLB.setText(iTotal);
        if(SubTotal > Total){
           ShowSubJLB.setText("0");
           ShowTotalJLB.setText("0");
        }
        double costOfTotal = Double.parseDouble(ShowTotalJLB.getText());

        /* Food food = new Food(chicken,hamburger,bacon,costOfDrink,costOfTotal,
            costOfTax,costOfDelivery,costOfSub);
        
        foodReceipt.add(food);  */
        try {
            String sql = ("insert into receipt(Chicken,Hamburger,Bacon,CostOfMeal,CostOfDelivery,CostOfDrink,CostOfSubTotal,CostOfTax,CostofTotal) values(?,?,?,?,?,?,?,?,?)");
            pat = conn.prepareStatement(sql);
            pat.setDouble(1, Double.parseDouble(NumOfFirstFood.getText()));
            pat.setDouble(2, Double.parseDouble(NumOfSecondFood.getText()));
            pat.setDouble(3, Double.parseDouble(NumOfThirdFood.getText()));
            pat.setDouble(4, Double.parseDouble(ShowCostOfMealsJLB.getText()));
            pat.setDouble(5, Double.parseDouble(ShowCostOfDelieryJLB.getText()));
            pat.setDouble(6, Double.parseDouble(ShowCostOfDrinksJlb.getText()));
            pat.setDouble(7, Double.parseDouble(ShowSubJLB.getText()));
            pat.setDouble(8, Double.parseDouble(ShowTaxJLB.getText()));
            pat.setDouble(9, Double.parseDouble(ShowTotalJLB.getText()));
            pat.execute();
            JOptionPane.showMessageDialog(null, "Stored succesfully!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_TotalBtnMouseClicked

    private void ReceiptBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReceiptBtnMouseClicked
        ReceiptArea.setText(null);
        double Qty1 = Double.parseDouble(NumOfFirstFood.getText());
        double Qty2 = Double.parseDouble(NumOfSecondFood.getText());
        double Qty3 = Double.parseDouble(NumOfThirdFood.getText());

        double costOfDrink = Double.parseDouble(ShowCostOfDrinksJlb.getText());
        double costOfDelivery = Double.parseDouble(ShowCostOfDelieryJLB.getText());
        double costOfTax = Double.parseDouble(ShowTaxJLB.getText());
        double costOfSub = Double.parseDouble(ShowSubJLB.getText());
        double costOfTotal = Double.parseDouble(ShowTotalJLB.getText());

        ReceiptArea.append("----------------------------------------------------\n\n"
                + "\tReceipt:\n\n"
                + Qty1 + " Chickens:            " + Qty1 * 5.5 + " USD" + " \n\n"
                + Qty2 + " Hamburgers:      " + Qty2 * 3.5 + " USD" + " \n\n"
                + Qty3 + " Bacon:               " + Qty3 * 6.5 + " USD" + " \n\n"
                + " drink    :                   " + costOfDrink + " USD" + "\n\n"
                + "Cost of Delivery:        " + costOfDelivery + " USD" + "\n\n"
                + "Cost of Tax:                " + costOfTax + " USD" + "\n\n"
                + "Cost of Sub:              " + costOfSub + " USD" + "\n\n"
                + "---------------------------------------------\n\n"
                + "Total :                         " + costOfTotal + " USD " + "\n\n");


    }//GEN-LAST:event_ReceiptBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceiptBtnActionPerformed


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ReceiptArea.setText(null);
        JTablee n1 = new JTablee();

    }//GEN-LAST:event_jButton1MouseClicked

    public double SubTotalFunction() {
        double Sub = (i[1] + i[2] + i[0]) / 100;
        return Sub;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BaconCB;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JComboBox<String> ChangeMoneyCB;
    private javax.swing.JCheckBox ChickenCB;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton ConvertBtn;
    private javax.swing.JPanel ConvertPanel;
    private javax.swing.JPanel CostPanel;
    private javax.swing.JLabel CostofDrinksJLB;
    private javax.swing.JLabel CostofHomeJlb;
    private javax.swing.JLabel CostofMealsJlb;
    private javax.swing.JLabel Drinksjlb;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JPanel FoodPanel;
    private javax.swing.JCheckBox HamburgerCB;
    private javax.swing.JCheckBox HomeDeliveryCB;
    private javax.swing.JTextField NumOfFirstFood;
    private javax.swing.JTextField NumOfSecondFood;
    private javax.swing.JTextField NumOfThirdFood;
    private javax.swing.JTextArea ReceiptArea;
    private javax.swing.JButton ReceiptBtn;
    private javax.swing.JPanel ReceiptPanel;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JComboBox<String> SelectDrinksCB;
    private javax.swing.JLabel ShowCostOfDelieryJLB;
    private javax.swing.JLabel ShowCostOfDrinksJlb;
    private javax.swing.JLabel ShowCostOfMealsJLB;
    private javax.swing.JLabel ShowMoneyJlb;
    private javax.swing.JLabel ShowSubJLB;
    private javax.swing.JLabel ShowTaxJLB;
    private javax.swing.JLabel ShowTotalJLB;
    private javax.swing.JLabel SubTotalJLB;
    private javax.swing.JCheckBox TaxCb;
    private javax.swing.JLabel TaxJLB;
    private javax.swing.JTextField TittleTxt;
    private javax.swing.JButton TotalBtn;
    private javax.swing.JLabel TotalJLb;
    private javax.swing.JPanel TotalPanel;
    private javax.swing.JTextField TypeMoneyTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
